name: Docker Build and Push # Renamed for clarity from "Docker Publish"

on:
  push:
    branches: ['**'] # Trigger workflow for pushes to all branches
    tags: ['v*.*.*']
  pull_request:
    branches: ['**'] # Trigger workflow for PRs to all branches

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Based on @tsconfig/node22

      # Add pnpm setup step
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # The version will be read from package.json's packageManager field

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm test:unit -- --coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    needs: test
    permissions:
      contents: read
      packages: write # This might not be strictly necessary for Docker Hub public repos, but doesn't hurt.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} # Do not push on PRs
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # build-args: | # if you need build arguments
          #   VITE_API_BASE_URL=${{vars.VITE_API_BASE_URL}}
          #   VITE_GA_ID=${{vars.VITE_GA_ID}}
